src/WoodGroveGroceriesWebApplication/Entities/Trolley.cs
namespace WoodGroveGroceriesWebApplication.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public class Trolley : EntityBase
    {
        private readonly List<TrolleyItem> _items = new List<TrolleyItem>();

        public IReadOnlyCollection<TrolleyItem> Items => _items.AsReadOnly();

        public string OwnerId { get; set; }

        public void AddItem(string catalogItemId, int quantity = 1)
        {
            var existingItem = Items.FirstOrDefault(item => item.CatalogItemId == catalogItemId);

            if (existingItem != null)
            {
                existingItem.Quantity += quantity;
                return;
            }

            var newItem = new TrolleyItem {Id = Guid.NewGuid().ToString(), CatalogItemId = catalogItemId, Quantity = quantity};

            _items.Add(newItem);
        }

        public void RemoveItem(string id)
        {
            var existingItem = Items.FirstOrDefault(item => item.Id == id);
            _items.Remove(existingItem);
        }
    }
}

src/WoodGroveGroceriesWebApplication/ViewModels/TrolleyViewModel.cs
namespace WoodGroveGroceriesWebApplication.ViewModels
{
    using System.Collections.Generic;

    public class TrolleyViewModel
    {
        public string Id { get; set; }

        public IList<TrolleyItemViewModel> Items { get; set; } = new List<TrolleyItemViewModel>();

        public string OwnerId { get; set; }
    }
}

src/WoodGroveGroceriesWebApplication/Controllers/TrolleyController.cs
namespace WoodGroveGroceriesWebApplication.Controllers
{
    using System;
    using System.Security.Claims;
    using System.Threading.Tasks;
    using Extensions;
    using Managers;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using ViewModels;
    using ViewServices;

    //[Authorize(Policy = Constants.AuthorizationPolicies.AccessTrolley)]
    public class TrolleyController : BaseController
    {
        private readonly ITrolleyManager _trolleyManager;
        private readonly ITrolleyViewService _trolleyViewService;

        public TrolleyController(ITrolleyViewService trolleyViewService, ITrolleyManager trolleyManager, IndustryManager industryManager) :
            base(industryManager)
        {
            _trolleyViewService = trolleyViewService ?? throw new ArgumentNullException(nameof(trolleyViewService));
            _trolleyManager = trolleyManager ?? throw new ArgumentNullException(nameof(trolleyManager));
        }

        [HttpPost]
        public async Task<IActionResult> AddFromCatalogToTrolley(CatalogItemViewModel catalogItemViewModel)
        {
            var trolleyViewModel = await GetTrolleyViewModelAsync();
            await _trolleyManager.AddToTrolleyAsync(trolleyViewModel.Id, catalogItemViewModel.Id, 1);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> AddFromPantryToTrolley(PantryItemViewModel pantryItemViewModel)
        {
            var trolleyViewModel = await GetTrolleyViewModelAsync();
            await _trolleyManager.AddToTrolleyAsync(trolleyViewModel.Id, pantryItemViewModel.CatalogItemId, 1);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Index()
        {
            var userIsInBusinessCustomerStockerRole = User.IsInBusinessCustomerStockerRole();

            var viewModel = new TrolleyIndexViewModel
            {
                AspController = userIsInBusinessCustomerStockerRole ? "Pantry" : "CatalogItem", Trolley = await GetTrolleyViewModelAsync()
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> RemoveFromTrolley(string id)
        {
            var trolleyViewModel = await GetTrolleyViewModelAsync();
            await _trolleyManager.RemoveFromTrolleyAsync(trolleyViewModel.Id, id);
            return RedirectToAction("Index");
        }

        private async Task<TrolleyViewModel> GetTrolleyViewModelAsync()
        {
            var userId = User.FindFirstValue(Constants.ClaimTypes.ObjectIdentifier);
            return await _trolleyViewService.GetOrCreateTrolleyForOwnerAsync(userId);
        }
    }
}

src/WoodGroveGroceriesWebApplication/Views/Trolley/Index.cshtml
@using WoodGroveGroceriesWebApplication.Extensions
@using WoodGroveGroceriesWebApplication.Managers
@model WoodGroveGroceriesWebApplication.ViewModels.TrolleyIndexViewModel
@{
    ViewBag.Title = "Cart";
    var industry = (IIndustry) ViewData["Industry"];
}

<style type="text/css">

    .allergy-info {
        display: block;
        left: 150px;
        max-height: 60px;
        max-width: 60px;
        position: relative;
        top: -150px;
    }
</style>


<main class="">
    <section class="section mb-5 pb-5">
        <div class="table-responsive">
            <table class="table trolley-table">
                @if (Model.Trolley.Items != null && Model.Trolley.Items.Count > 0)
                {
                    <thead>
                    <tr>
                        <th></th>
                        <th class="font-weight-bold">
                            <strong>@industry.TrolleyProductHeading</strong>
                        </th>
                        @if (industry.ItemMultiPurchasable)
                        {
                            <th class="font-weight-bold">
                                <strong>Quantity</strong>
                            </th>
                            <th></th>
                        }

                    </tr>
                    </thead>
                }
                <tbody>

                @if (Model.Trolley.Items != null && Model.Trolley.Items.Count > 0)
                {
                    foreach (var item in Model.Trolley.Items)
                    {
                        <tr>
                            <th scope="row">
                                <img alt="@item.ProductName" class="img-fluid z-depth-0" src="@item.ProductPictureUrl">

                                @if (User.IsAllergicTo(item.ProductAllergyInfo))
                                {
                                    <img alt="" class="allergy-info" src="@industry.CartAlertIndicator">
                                }
                            </th>
                            <td>
                                <h5 class="mt-3">
                                    <strong>@item.ProductName</strong>
                                </h5>
                            </td>
                            @if (industry.ItemMultiPurchasable)
                            {
                                <td class="text-center text-md-left">
                                    <span class="qty">@item.Quantity</span>
                                </td>
                            }

                            <td>
                                <form asp-controller="Trolley" asp-action="RemoveFromTrolley" method="post">
                                    <input name="Id" type="hidden" value="@item.Id"/>
                                    <button class="btn btn-wg-green btn-rounded btn-sm waves-effect waves-light" title="" type="submit" data-original-title="Remove item" data-placement="top" data-toggle="tooltip">X</button>
                                </form>
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td class="text-center text-md-left" colspan="3">
                            <h5 class="mt-3">
                                @industry.TrolleyCartEmpty
                            </h5>
                        </td>
                    </tr>
                }
                <tr>
                    <td colspan="4" class="text-center">
                        <a class="btn btn-wg-green btn-md btn-rounded waves-effect waves-light" asp-controller="@Model.AspController" asp-action="Index">@industry.TrolleyContinueShopping</a>

                        @if (Model.Trolley.Items.Count > 0)
                        {
                            <a class="btn btn-wg-green btn-md btn-rounded waves-effect waves-light" asp-controller="Account" asp-action="MFA">@industry.TrolleyCompletePurchase</a>
                        }

                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </section>
</main>